name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "01ac09ef-09ef-45a4-84da-1b3bffc41695"

[[kv_namespaces]]
binding = "kv"
id = "d995962079a44a5b8650c02ce9d6c12e"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

#[[send_email]]
#name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["*/30 * * * *", "0 16 * * *"]

[vars]
domain = ["terapi5menitseft.com"]
admin = "akbar@terapi5menitseft.com"
jwt_secret = "cM7kR3nP9xQ2vZ5wY8tA4bD6eF1hJ0iL"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
